esphome:
  name: "dimmer-v2"
  friendly_name: Dimmer V2

esp8266:
  board: esp01_1m
  restore_from_flash: true

logger:
  level: debug

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dimmer V2"
    password: !secret wifi_password

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: "pablo"
  password: !secret mqtt_password
  id: mqtt_client

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: GPIO12
    init_with_half_cycle: true
    zero_cross_pin:
      number: GPIO13
      mode:
        input: true
      inverted: yes

light:
  - platform: monochromatic
    restore_mode: ALWAYS_OFF 
    output: dimmer1
    name: Dimmerized Light
    gamma_correct: 4.0